# Generated by Django 5.1.3 on 2025-04-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_color_person_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Color',
            new_name='color',
        ),
    ]
